apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kafka
  namespace: messaging
spec: 
  interval: 5m
  releaseName: kafka
  chart: 
    spec:
      chart: kafka
      version: 26.5.0
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system-kafka-helm
values:
  fullnameOverride: kafka
  replicaCount: 1
  zookeeper:
    enabled: true
    replicaCount: 1
  persistence:
    enabled: false
