apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: kustomization
metadata:
  name: kafka-infra
  namespace: flux-system-kafka-helm
spec:
  interval: 5m
  path: ./clusters/minikube
  prune: true
  sourceRef: 
     kind: GitRepository
     name: flux-system-kafka-helm
  validation: client
  targetNamespace: messaging
