apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kafka-infra
  namespace: flux-system-kafka-helm
spec:
  interval: 1m
  path: flux-kafka-demo/clusters/minikube/
>>>>>>> 5b12b8f3a1863817b14ea098d95ea340d0178459
  prune: true
  sourceRef: 
    kind: GitRepository
    name: flux-system-kafka-helm
  validation: client
  targetNamespace: messaging
