apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: kafka-infra
  namespace: flux-system-kafka-helm
spec:
  interval: 1m
  path: flux-kafka-demo/clusters/minikube/
  prune: true
  sourceRef: 
    kind: GitRepository
    name: flux-kafka-demo
  validation: client
  targetNamespace: messaging
