apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - kafka-source.yaml
  - kafka-helmrelease.yaml
metadata:
  name: kafka-infra
  namespace: flux-system-kafka-namespace
spec:
  interval: 1m
  path: flux-kafka-demo/clusters/minikube/
  prune: true
  sourceRef: 
    kind: GitRepository
    name: flux-kafka-demo
  validation: client
  targetNamespace: messaging
l


